/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.DirectorDAO;
import dao.GestionDao;
import dao.PeliculaDAO;
import excepciones.DirectorException;
import excepciones.PeliculaException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Director;
import model.Pelicula;

/**
 *
 * @author alex
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() throws SQLException {
        this.setLocationRelativeTo(null);
        initComponents();
        lblOculto.setVisible(false);
        lblOculto1.setVisible(false);
        cargarDesplegables();
        
        
        
    }
    
    public void cargarDesplegables() throws SQLException{
        GestionDao gDao = new GestionDao();
        DirectorDAO dDao = new DirectorDAO();
        PeliculaDAO pDao = new PeliculaDAO();
        gDao.conectar();
        ArrayList<Director> listaDirectores = dDao.extraerDirectores();
        ArrayList<Pelicula> listaPeliculas = pDao.extraerPeliculas();
        ArrayList<String> listaGeneros = pDao.extraerGeneros();
        gDao.desconectar();
        cbxSeleccioneDirector.removeAllItems();
        cbxSeleccioneDirector1.removeAllItems();
        cbxSeleccionePelicula.removeAllItems();
        cbxDirectores.removeAllItems();
        cbxDirectores.addItem("");
        cbxGenero.removeAllItems();
        cbxGenero.addItem("");
        for(int i = 0; i < listaDirectores.size(); i++){
            cbxSeleccioneDirector.addItem(listaDirectores.get(i).getNombre() + " " + listaDirectores.get(i).getApellidos());
            cbxSeleccioneDirector1.addItem(listaDirectores.get(i).getNombre() + " " + listaDirectores.get(i).getApellidos());
            cbxDirectores.addItem(listaDirectores.get(i).getNombre() + " " + listaDirectores.get(i).getApellidos());
        }
        for(int i = 0; i < listaPeliculas.size(); i++){
            cbxSeleccionePelicula.addItem(listaPeliculas.get(i).getTitulo());
        }
        for(int i = 0; i < listaGeneros.size(); i++){
            cbxGenero.addItem(listaGeneros.get(i));
        }
    }
    
    public void crearAviso(String mensaje){
        Aviso ventanaAviso = new Aviso(this, true, mensaje);
        ventanaAviso.setLocationRelativeTo(null);
        ventanaAviso.setResizable(false);
        ventanaAviso.setVisible(true);
        System.out.println("Aviso Creado");
    }
    
    public void crearVentanaModificarDirector(String apellidos) throws SQLException{
        VentanaModificarDirector ventanaMD = new VentanaModificarDirector(this, true, apellidos);
        ventanaMD.setLocationRelativeTo(null);
        ventanaMD.setResizable(false);
        ventanaMD.setVisible(true);
        System.out.println("Ventana de modificación de director creada");
    }
    
    public void crearVentanaModificarPelicula(String titulo) throws SQLException{
        VentanaModificarPelicula ventanaMP = new VentanaModificarPelicula(this, true, titulo);
        ventanaMP.setLocationRelativeTo(null);
        ventanaMP.setResizable(false);
        ventanaMP.setVisible(true);
        System.out.println("Ventana de modificación de película creada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        btnAñadirDirector = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbxSeleccioneDirector = new javax.swing.JComboBox<>();
        lblSeleccioneDirector = new javax.swing.JLabel();
        btnModificarDirector = new javax.swing.JButton();
        btnEliminarDirector = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblGenero1 = new javax.swing.JLabel();
        cbxSeleccioneDirector1 = new javax.swing.JComboBox<>();
        btnAñadirPelicula = new javax.swing.JButton();
        lblSeleccionePelicula = new javax.swing.JLabel();
        cbxSeleccionePelicula = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        btnModificarPelicula = new javax.swing.JButton();
        btnEliminarPelicula = new javax.swing.JButton();
        lblOculto = new javax.swing.JLabel();
        lblOculto1 = new javax.swing.JLabel();
        lblDirectores = new javax.swing.JLabel();
        cbxDirectores = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblSeleccioneGenero = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        btnFiltrarDirector = new javax.swing.JButton();
        btnFiltrarGenero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FILMOTECA");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel1.setText("DIRECTOR");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel2.setText("PELICULA");

        lblNombre.setText("Nombre:");

        lblApellidos.setText("Apellidos:");

        btnAñadirDirector.setText("Añadir Director");
        btnAñadirDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirDirectorActionPerformed(evt);
            }
        });

        cbxSeleccioneDirector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSeleccioneDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccioneDirectorActionPerformed(evt);
            }
        });

        lblSeleccioneDirector.setText("Seleccione Director");

        btnModificarDirector.setText("Modificar Director");
        btnModificarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDirectorActionPerformed(evt);
            }
        });

        btnEliminarDirector.setText("Eliminar Director");
        btnEliminarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDirectorActionPerformed(evt);
            }
        });

        lblTitulo.setText("Título:");

        lblPais.setText("País:");

        lblDuracion.setText("Duración:");

        lblGenero.setText("Género:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblGenero1.setText("Director:");

        cbxSeleccioneDirector1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAñadirPelicula.setText("Añadir Película");
        btnAñadirPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPeliculaActionPerformed(evt);
            }
        });

        lblSeleccionePelicula.setText("Seleccione Película:");

        cbxSeleccionePelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnModificarPelicula.setText("Modificar Pelicula");
        btnModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPeliculaActionPerformed(evt);
            }
        });

        btnEliminarPelicula.setText("Eliminar Pelicula");
        btnEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliculaActionPerformed(evt);
            }
        });

        lblOculto.setForeground(new java.awt.Color(249, 6, 6));
        lblOculto.setText("jLabel3");

        lblOculto1.setForeground(new java.awt.Color(246, 13, 13));
        lblOculto1.setText("jLabel3");

        lblDirectores.setText("Seleccione Director:");

        cbxDirectores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblSeleccioneGenero.setText("Seleccione Género:");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltrarDirector.setText("Filtrar");
        btnFiltrarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarDirectorActionPerformed(evt);
            }
        });

        btnFiltrarGenero.setText("Filtrar");
        btnFiltrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lblSeleccioneDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(cbxSeleccioneDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(76, 76, 76))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(btnModificarDirector)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarDirector)
                            .addGap(39, 39, 39))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addComponent(jSeparator6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre)
                                .addComponent(lblApellidos))
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addComponent(btnAñadirDirector))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(lblOculto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFiltrarDirector)
                            .addComponent(lblDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTitulo)
                                                    .addComponent(lblPais)
                                                    .addComponent(lblDuracion)
                                                    .addComponent(lblGenero)
                                                    .addComponent(lblGenero1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbxSeleccioneDirector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtTitulo)
                                                        .addComponent(txtPais)
                                                        .addComponent(txtDuracion)
                                                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSeleccionePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxSeleccionePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(btnModificarPelicula)
                                                .addGap(28, 28, 28)
                                                .addComponent(btnEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 102, Short.MAX_VALUE))
                                    .addComponent(jSeparator3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOculto1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAñadirPelicula))
                                .addGap(158, 158, 158))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lblSeleccioneGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFiltrarGenero)
                                .addGap(176, 176, 176))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDuracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenero1)
                            .addComponent(cbxSeleccioneDirector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(btnAñadirPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOculto1)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeleccionePelicula)
                            .addComponent(cbxSeleccionePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarPelicula)
                            .addComponent(btnEliminarPelicula)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidos)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnAñadirDirector)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOculto)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSeleccioneDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccioneDirector))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarDirector)
                            .addComponent(btnEliminarDirector)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDirectores)
                                    .addComponent(cbxDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(btnFiltrarDirector))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeleccioneGenero)
                            .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnFiltrarGenero)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSeleccioneDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccioneDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeleccioneDirectorActionPerformed

    private void btnAñadirDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirDirectorActionPerformed
        DirectorDAO dDao = new DirectorDAO();
        GestionDao gDao = new GestionDao();
        
        if(txtNombre.getText().isEmpty() || txtApellidos.getText().isEmpty()){
            lblOculto.setText("El nombre y apellidos no pueden estar vacíos");
            lblOculto.setVisible(true);
            
        }else{
            Director d = new Director();
            d.setNombre(txtNombre.getText());
            d.setApellidos(txtApellidos.getText());
            try {
                dDao.insertarDirector(d);
                cargarDesplegables();
                
            } catch (DirectorException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtNombre.setText(null);
        txtApellidos.setText(null);
    }//GEN-LAST:event_btnAñadirDirectorActionPerformed

    private void btnModificarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDirectorActionPerformed
        String directorString = cbxSeleccioneDirector.getSelectedItem().toString();
        DirectorDAO dDao = new DirectorDAO();
                
        try {dDao.modificarDirector(directorString);
            cargarDesplegables();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarDirectorActionPerformed

    private void btnEliminarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDirectorActionPerformed
        String directorEliminarString = cbxSeleccioneDirector.getSelectedItem().toString();
        DirectorDAO dDao = new DirectorDAO();
        
        try {dDao.eliminarDirector(directorEliminarString);
            cargarDesplegables();
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnEliminarDirectorActionPerformed

    private void btnAñadirPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPeliculaActionPerformed
        PeliculaDAO pDao = new PeliculaDAO();
        GestionDao gDao = new GestionDao();
        DirectorDAO dDao = new DirectorDAO();
        boolean duracionParseada = pDao.parsearStringInteger(txtDuracion.getText());
        
        if(txtTitulo.getText().isEmpty() || txtPais.getText().isEmpty() || txtDuracion.getText().isEmpty() || txtGenero.getText().isEmpty() || cbxSeleccioneDirector1.getSelectedItem() == null){
            lblOculto1.setText("Debe rellenar todos los campos.");
            lblOculto1.setVisible(true);
            
        }else if(duracionParseada != true){
            lblOculto1.setText("Introduzca un número valido en Duración.");
            lblOculto1.setVisible(true);
            
        }else{            
            Pelicula p = new Pelicula();
            p.setTitulo(txtTitulo.getText());
            p.setPais(txtPais.getText());
            p.setDuracion(Integer.parseInt(txtDuracion.getText()));
            p.setGenero(txtGenero.getText());
            String director = cbxSeleccioneDirector1.getSelectedItem().toString();
            Director directorObjeto = dDao.obtenerDirectorModificarEliminar(director);
            int iddirector;
            try {
                iddirector = dDao.obteneriddirector(directorObjeto);
                p.setIddirector(iddirector);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                pDao.insertarPelicula(p);
                cargarDesplegables();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DirectorException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtTitulo.setText(null);
        txtPais.setText(null);
        txtGenero.setText(null);
        txtDuracion.setText(null);
    }//GEN-LAST:event_btnAñadirPeliculaActionPerformed

    private void btnEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliculaActionPerformed
        String peliculaEliminarString = cbxSeleccionePelicula.getSelectedItem().toString();
        PeliculaDAO pDao = new PeliculaDAO();
        
        try {pDao.eliminarPelicula(peliculaEliminarString);
            cargarDesplegables();
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarPeliculaActionPerformed

    private void btnModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPeliculaActionPerformed
        String peliculaString = cbxSeleccionePelicula.getSelectedItem().toString();
        PeliculaDAO pDao = new PeliculaDAO();
                
        try {pDao.modificarPelicula(peliculaString);
            cargarDesplegables();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarPeliculaActionPerformed

    private void btnFiltrarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarDirectorActionPerformed
        String filtroDirector = cbxDirectores.getSelectedItem().toString();
        PeliculaDAO pDao = new PeliculaDAO();
        DirectorDAO dDao = new DirectorDAO();
        
        if(filtroDirector == ""){
            try {
                ArrayList<Pelicula> listaCompleta = pDao.mostrarPeliculas();
                VentanaVisualizarPeliculas vvp = new VentanaVisualizarPeliculas(listaCompleta);
                
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PeliculaException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            
            try {int iddirector = dDao.obtenerIdDirector(filtroDirector);
                ArrayList<Pelicula> listaPorDirector = pDao.mostrarPeliculasPorDirector(iddirector);
                VentanaVisualizarPeliculas vvp = new VentanaVisualizarPeliculas(listaPorDirector);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PeliculaException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnFiltrarDirectorActionPerformed

    private void btnFiltrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarGeneroActionPerformed
        String filtroGenero = cbxGenero.getSelectedItem().toString();
        PeliculaDAO pDao = new PeliculaDAO();
        DirectorDAO dDao = new DirectorDAO();
        
        if(filtroGenero == ""){
            try {
                ArrayList<Pelicula> listaCompleta = pDao.mostrarPeliculas();
                VentanaVisualizarPeliculas vvp = new VentanaVisualizarPeliculas(listaCompleta);
                
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PeliculaException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            
            try {
                ArrayList<Pelicula> listaPorGenero = pDao.mostrarPeliculasPorGenero(filtroGenero);
                VentanaVisualizarPeliculas vvp = new VentanaVisualizarPeliculas(listaPorGenero);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PeliculaException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnFiltrarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VentanaPrincipal vp = new VentanaPrincipal();
                    vp.setVisible(true);
                    vp.setLocationRelativeTo(null);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirDirector;
    private javax.swing.JButton btnAñadirPelicula;
    private javax.swing.JButton btnEliminarDirector;
    private javax.swing.JButton btnEliminarPelicula;
    private javax.swing.JButton btnFiltrarDirector;
    private javax.swing.JButton btnFiltrarGenero;
    private javax.swing.JButton btnModificarDirector;
    private javax.swing.JButton btnModificarPelicula;
    private javax.swing.JComboBox<String> cbxDirectores;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxSeleccioneDirector;
    private javax.swing.JComboBox<String> cbxSeleccioneDirector1;
    private javax.swing.JComboBox<String> cbxSeleccionePelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDirectores;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGenero1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOculto;
    private javax.swing.JLabel lblOculto1;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblSeleccioneDirector;
    private javax.swing.JLabel lblSeleccioneGenero;
    private javax.swing.JLabel lblSeleccionePelicula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
