/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.DirectorDAO;
import dao.GestionDao;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Director;

/**
 *
 * @author alex
 */
public class VentanaModificarDirector extends javax.swing.JDialog {
    private String apellidos;
    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificarDirector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblOculto.setVisible(false);
    }
    
    public VentanaModificarDirector(java.awt.Frame parent, boolean modal, String apellidos) {
        super(parent, modal);
        initComponents();
        lblOculto.setVisible(false);
        this.apellidos = apellidos;
    }
    
    public Director crearDirectorModificado(){
        Director directorModificado = new Director();
        try {VentanaPrincipal vp = new VentanaPrincipal();
            directorModificado.setNombre(txtNuevoNombre.getText());
            directorModificado.setApellidos(txtNuevoApellido.getText());
            return directorModificado;
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaModificarDirector.class.getName()).log(Level.SEVERE, null, ex);
        }   
        return directorModificado;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModificarDirector = new javax.swing.JLabel();
        lblNuevoNombre = new javax.swing.JLabel();
        lblNuevoApellido = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        txtNuevoApellido = new javax.swing.JTextField();
        btnModificarDirector = new javax.swing.JToggleButton();
        lblOculto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModificarDirector.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        lblModificarDirector.setText("MODIFICAR DIRECTOR");

        lblNuevoNombre.setText("Nuevo Nombre:");

        lblNuevoApellido.setText("Nuevos Apellidos:");

        btnModificarDirector.setText("Modificar");
        btnModificarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDirectorActionPerformed(evt);
            }
        });

        lblOculto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarDirector)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModificarDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNuevoNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNuevoApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblOculto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModificarDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOculto)
                .addGap(14, 14, 14)
                .addComponent(btnModificarDirector)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void btnModificarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDirectorActionPerformed
        Director directorModificado = null;
        if(txtNuevoNombre.getText().isEmpty() || txtNuevoApellido.getText().isEmpty()){
                lblOculto.setText("El nombre y apellidos no pueden estar vacíos");
                lblOculto.setVisible(true);
        }else{
            directorModificado = crearDirectorModificado();
           
            try {GestionDao gDao = new GestionDao();
                VentanaPrincipal vp = new VentanaPrincipal();
                DirectorDAO dDao = new DirectorDAO();
                boolean existe = dDao.existeDirector(directorModificado);
                if(existe){
                    vp.crearAviso("Director existente.");
                }else{

                    try { String update = "UPDATE director SET nombre = ?, apellidos = ? where apellidos = ?;";
                        gDao.conectar();
                        PreparedStatement ps = GestionDao.conexion.prepareStatement(update);
                        ps.setString(1, directorModificado.getNombre());
                        ps.setString(2, directorModificado.getApellidos());
                        ps.setString(3, apellidos);
                        ps.executeUpdate();
                        ps.close();
                        gDao.desconectar();
                        vp.crearAviso("Director modificado.");
                    } catch (SQLException ex) {
                        Logger.getLogger(VentanaModificarDirector.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaModificarDirector.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
               
    }//GEN-LAST:event_btnModificarDirectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaModificarDirector dialog = new VentanaModificarDirector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnModificarDirector;
    private javax.swing.JLabel lblModificarDirector;
    private javax.swing.JLabel lblNuevoApellido;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JLabel lblOculto;
    private javax.swing.JTextField txtNuevoApellido;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
